//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransactionDetails
    {
        public int BankTransactionDetailsId { get; set; }
        public int BankTransactionId { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string BankTransactionReturnId { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual BankTransactions BankTransactions { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
    }
}
