//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransactions
    {
        public BankTransactions()
        {
            this.BankTransactionDetails = new HashSet<BankTransactionDetails>();
        }
    
        public int TransactionId { get; set; }
        public int OwnerId { get; set; }
        public int RentalId { get; set; }
        public int ContractId { get; set; }
    
        public virtual ICollection<BankTransactionDetails> BankTransactionDetails { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual Contracts Contracts1 { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Rentals Rentals { get; set; }
    }
}
