//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public Contracts()
        {
            this.BankTransactions = new HashSet<BankTransactions>();
            this.BankTransactions1 = new HashSet<BankTransactions>();
        }
    
        public int ContractId { get; set; }
        public int RentalId { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool EmailService { get; set; }
        public bool SMSService { get; set; }
        public int UserId { get; set; }
        public bool Active { get; set; }
        public System.DateTime Dated { get; set; }
        public int CurrencyId { get; set; }
        public decimal Price { get; set; }
        public int OrganizationId { get; set; }
        public int UnitId { get; set; }
        public string Descriptions { get; set; }
    
        public virtual ICollection<BankTransactions> BankTransactions { get; set; }
        public virtual ICollection<BankTransactions> BankTransactions1 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Rentals Rentals { get; set; }
        public virtual Units Units { get; set; }
    }
}
