//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Districts
    {
        public Districts()
        {
            this.Streets = new HashSet<Streets>();
        }
    
        public int DistricId { get; set; }
        public string EnglishName { get; set; }
        public int CitiyId { get; set; }
        public string ArabicName { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual ICollection<Streets> Streets { get; set; }
    }
}
