//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUserAction
    {
        public long SystemTransationId { get; set; }
        public System.DateTime LogDate { get; set; }
        public string PageUrl { get; set; }
        public string PageName { get; set; }
        public int UserId { get; set; }
        public string LogAction { get; set; }
        public string IPAddress { get; set; }
    }
}
