//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public Modules()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int ModuleId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public int Priority { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
