//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nationalities
    {
        public Nationalities()
        {
            this.Owners = new HashSet<Owners>();
            this.Rentals = new HashSet<Rentals>();
            this.Users = new HashSet<Users>();
        }
    
        public int NationalityId { get; set; }
        public string EnglishName { get; set; }
        public string ArabicName { get; set; }
    
        public virtual ICollection<Owners> Owners { get; set; }
        public virtual ICollection<Rentals> Rentals { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
