//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owners
    {
        public Owners()
        {
            this.BankTransactions = new HashSet<BankTransactions>();
            this.Contracts = new HashSet<Contracts>();
            this.TransactionLogs = new HashSet<TransactionLogs>();
            this.Units = new HashSet<Units>();
        }
    
        public int OwnerId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Exist { get; set; }
        public System.DateTime Dated { get; set; }
        public int UserId { get; set; }
        public int OrganizationId { get; set; }
        public string SSN { get; set; }
        public bool Deleted { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; }
        public int NationalityId { get; set; }
    
        public virtual ICollection<BankTransactions> BankTransactions { get; set; }
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual Nationalities Nationalities { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<TransactionLogs> TransactionLogs { get; set; }
        public virtual ICollection<Units> Units { get; set; }
    }
}
