//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLogs
    {
        public long TransactionLogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RentalId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> UnitPriceId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public int TransactionLogTypeId { get; set; }
        public System.DateTime Dated { get; set; }
        public int TransactionUserId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Rentals Rentals { get; set; }
        public virtual TransactionLogTypes TransactionLogTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
