//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public Units()
        {
            this.Contracts = new HashSet<Contracts>();
            this.UnitPrices = new HashSet<UnitPrices>();
        }
    
        public int UnitId { get; set; }
        public int UnitNumber { get; set; }
        public string UnitName { get; set; }
        public int StreetId { get; set; }
        public int UnitTypeId { get; set; }
        public int OwnerId { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Streets Streets { get; set; }
        public virtual ICollection<UnitPrices> UnitPrices { get; set; }
        public virtual UnitTypes UnitTypes { get; set; }
    }
}
